spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/full_marks?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: admin
server:
  port: 8079